apiVersion: v1
kind: ConfigMap
metadata:
  name: sftp-sshd-config
  namespace: sftp
data:
  sshd_config: |
    Protocol 2
    HostKey /etc/ssh/ssh_host_ed25519_key
    HostKey /etc/ssh/ssh_host_rsa_key
    UseDNS no
    PermitRootLogin no
    X11Forwarding no
    AllowTcpForwarding no
    Subsystem sftp internal-sftp
    ForceCommand internal-sftp
    ChrootDirectory %h
    PasswordAuthentication no
    LogLevel DEBUG3
    TCPKeepAlive yes
    ClientAliveInterval 60
    ClientAliveCountMax 40000