apiVersion: v1
kind: ConfigMap
metadata:
  name: sftp-permissions-config
  namespace: sftp
data:
  change_permissions.sh: |
    #!/bin/bash
    #File mounted as: /etc/sftp.d/change_permissions.sh
    chown root:root /home
    chmod 755 /home
    
    chown -R usera:users /home/user1/incoming
    chown -R usera:users /home/user1/outgoing
    chmod -R 755 /home/user1/incoming
    chmod -R 755 /home/user1/outgoing
