apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  namespace: sftp
  labels:
    app: sftp
spec:
  selector:
    matchLabels:
      app: sftp
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: sftp
    spec:
      volumes:
        - name: sftp-data
          emptyDir:
            sizeLimit: 50Mi
        - name: sftp-config
          emptyDir:
            sizeLimit: 50Mi
        - name: sftp-sshd-config
          configMap:
            name: sftp-sshd-config
            items:
              - key: sshd_config
                path: sshd_config
        - name: sftp-permissions-config
          configMap:
            name: sftp-permissions-config
            defaultMode: 0744
            items:
              - key: change_permissions.sh
                path: change_permissions.sh
        - name: secret-ssh-keys2
          secret:
            secretName: secret-ssh-keys
            items: #should be permission 644
              - key: user1_rsa_key.pub
                path: id_rsa.pub
      containers:
        - name: sftp
          image: atmoz/sftp:latest
          imagePullPolicy: Always
          args: ["usera:password:1001:100:incoming,outgoing"] #create users and dirs
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: /home/
              name: sftp-data
              readOnly: false
            - mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
              name: sftp-sshd-config
              readOnly: false
            - mountPath: /etc/sftp.d/change_permissions.sh
              subPath: change_permissions.sh
              name: sftp-permissions-config
              readOnly: false
            - mountPath: /home/usera/.ssh/keys/id_rsa.pub
              subPath: id_rsa.pub
              name: secret-ssh-keys2
              readOnly: false
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
          resources: {}
        - name: busybox
          image: busybox:latest
          imagePullPolicy: Always
          command: [ "sh", "-c", "tail -f /dev/null" ]
          volumeMounts:
            - mountPath: /home/
              name: sftp-data
              readOnly: false



