kind: Service
apiVersion: v1
metadata:
  name: sftp
  namespace: sftp
  labels:
    environment: production
spec:
  type: "ClusterIP"
  ports:
    - name: "ssh"
      port: 22
      targetPort: 22
  selector:
    app: sftp