apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sftp
  namespace: sftp
  labels:
    app: sftp
spec:
  selector:
    matchLabels:
      app: sftp
  replicas: 3
  serviceName: sftp-headless
  template:
    metadata:
      labels:
        app: sftp
    spec:
      volumes:
        - name: sftp-sshd-config
          configMap:
            name: sftp-sshd-config
            items:
              - key: sshd_config
                path: sshd_config
        - name: sftp-users-config
          configMap:
            name: sftp-users-config
            items:
              - key: users.conf
                path: users.conf
        - name: sftp-permissions-config
          configMap:
            name: sftp-permissions-config
            defaultMode: 0744
            items:
              - key: change_permissions.sh
                path: change_permissions.sh
        - name: secret-ssh-keys
          secret:
            secretName: secret-ssh-keys
            defaultMode: 0400
        - name: secret-server-keys
          secret:
            secretName: secret-server-keys
            defaultMode: 0400
      containers:
        - name: sftp
          image: atmoz/sftp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: /home/
              name: sftp-data
              readOnly: false
            - mountPath: /etc/ssh
              name: sftp-config
              readOnly: false
            - mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
              name: sftp-sshd-config
              readOnly: false
            - mountPath: /etc/sftp/users.conf
              subPath: users.conf
              name: sftp-users-config
              readOnly: false
            - mountPath: /home/user1/.ssh/keys/user1_rsa_key
              subPath: user1_rsa_key
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /home/user1/.ssh/keys/user1_rsa_key.pub
              subPath: user1_rsa_key.pub
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /home/user1/.ssh/keys/user2_rsa_key
              subPath: user2_rsa_key
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /home/user2/.ssh/keys/user2_rsa_key.pub
              subPath: user2_rsa_key.pub
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /home/user3/.ssh/keys/user3_rsa_key
              subPath: user3_rsa_key
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /home/user3/.ssh/keys/user3_rsa_key.pub
              subPath: user3_rsa_key.pub
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_rsa_key
              subPath: ssh_host_rsa_key
              name: secret-server-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_rsa_key.pub
              subPath: ssh_host_rsa_key.pub
              name: secret-server-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ed25519_key
              subPath: ssh_host_ed25519_key
              name: secret-server-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ed25519_key.pub
              subPath: ssh_host_ed25519_key.pub
              name: secret-server-keys
              readOnly: true
            - mountPath: /etc/sftp.d/change_permissions.sh
              subPath: change_permissions.sh
              name: sftp-permissions-config
              readOnly: false
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
          resources: {}
        - name: busybox
          image: busybox:latest
          imagePullPolicy: Always
          command: [ "sh", "-c", "tail -f /dev/null" ]
          volumeMounts:
            - mountPath: /home/
              name: sftp-data
              readOnly: false
            - mountPath: /etc/ssh
              name: sftp-config
              readOnly: false
            - mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
              name: sftp-sshd-config
              readOnly: false
            - mountPath: /home/user1/.ssh/keys/user1_rsa_key
              subPath: user1_rsa_key
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /home/user1/.ssh/keys/user1_rsa_key.pub
              subPath: user1_rsa_key.pub
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /home/user2/.ssh/keys/user2_rsa_key
              subPath: user2_rsa_key
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /home/user2/.ssh/keys/user2_rsa_key.pub
              subPath: user2_rsa_key.pub
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /home/user3/.ssh/keys/user3_rsa_key
              subPath: user3_rsa_key
              name: secret-ssh-keys
              readOnly: true
            - mountPath: /home/user3/.ssh/keys/user3_rsa_key.pub
              subPath: user3_rsa_key.pub
              name: secret-ssh-keys
              readOnly: true
  volumeClaimTemplates:
    - metadata:
        name: sftp-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: sftp-config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Mi

